[package]
name = "opengl-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glam = "0.27.0"
glfw = "0.55.0"
once_cell = "1.19.0"
stb_image = "0.3.0"
